config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  root to: "home#index"
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { registrations: "devise_registrations", passwords: "devise_passwords" }
  get "/users/sign_in" => redirect("/")

  resources :home
  resources :contact_messages, only: [:new, :create]
  resources :customer_emergency_contacts, only: [:edit, :new, :create, :update, :destroy]
  resources :customer_vet_infos, only: [:edit, :new, :create, :update, :destroy]
  resources :hours_of_operations, only: [:edit, :update, :create, :destroy]
  resources :holidays
  resources :breed_restrictions
  resources :pets, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :amenities, only: [:new, :create, :update, :destroy, :edit]
  resources :policies, only: [:new, :create, :update, :destroy, :edit]
  resources :photos, only: [:new, :create, :update, :destroy, :edit]
  get '/reservations/old', to: "reservations#old_reservations", as: :old_reservation
  get '/get_pets', to: "reservations#get_pets", as: :get_pets

  resources :reservations, only: [:show, :new, :create]
  resources :kennel_ratings, only: [:new, :create]
  resources :stand_by_reservations, only: [:new, :create]
  resources :check_in_check_out_reservations, only: [:update]
  resources :check_in_contract_important_informations, only: [:update, :edit]
  resources :check_in_contract_reservation_changes, only: [:update, :edit]
  resources :check_in_contract_refund_policies, only: [:update, :edit]
  resources :press_pages

  # CsvKennelsController
    resources :csv_kennels
    post '/notify_kennel', to: 'csv_kennels#notify_kennel', as: :notify_kennel
    get '/claim_business', to: 'csv_kennels#claim_business', as: :claim_business
    post '/send_business_claim', to: 'csv_kennels#send_business_claim', as: :send_business_claim


  # PawbookingsAdminsController
   resources :pawbookings_admins, only: [:index]
   get '/admin_reservation_search', to: "pawbookings_admins#admin_reservation_search", as: :admin_reservation_search

   get '/refund_reservation_select', to: "pawbookings_admins#refund_reservation_select", as: :refund_reservation_select
   get '/refund_reservation_confirm', to: "pawbookings_admins#refund_reservation_confirm", as: :refund_reservation_confirm

   get '/update_reservation', to: "pawbookings_admins#update_reservation", as: :update_reservation

  # RunsController
    resources :runs, only: [:new, :create, :update, :destroy, :edit]
    delete "/delete_run_image", to: "runs#delete_run_image", as: :delete_run_image

  # PaymentsController
    resources :payments, only: [:new, :create]
    get "/vaccination_upload_after_payment", to: "payments#vaccination_upload_after_payment", as: :vaccination_upload_after_payment

  # KennelsController
    resources :kennels, only: [:new, :create, :update, :show, :edit, :index, :destroy]
    get "/kennel_dashboard",   to: "kennels#kennel_dashboard",   as: :kennel_dashboard
    get "/kennel_reservations", to: "kennels#kennel_reservations", as: :kennel_reservations
    get "/kennel_view_pets", to: "kennels#kennel_view_pets", as: :kennel_view_pets
    get '/search_reservations', to: "kennels#search_reservations", as: :search_reservations
    match "/kennel_searched_reservation", to: "kennels#kennel_searched_reservation", as: :kennel_searched_reservation, via: [:get, :post]

  # CustomersController
    get "/customer_dashboard", to: "customers#customer_dashboard", as: :customer_dashboard
    post "/create_user_image", to: "customers#create_user_image", as: :create_user_image
    delete "/delete_user_image", to: "customers#delete_user_image", as: :delete_user_image

  # SearchesController
    resources :searches, only: [:create]
    get "/search_results", to: "searches#search_results", as: :search_results

  # BlogsController
    resources :blogs
    match "/blog_search", to: "blogs#blog_search", as: :blog_search, via: [:get, :post]
    get "/all_blogs", to: "blogs#all_blogs", as: :all_blogs

  # BlogCategoriesController
    resources :blog_categories
    get "/all_blog_categories", to: "blog_categories#all_blog_categories", as: :all_blog_categories

  # Contracts
    match "/customer_checkin_contract", to: "contracts#customer_checkin_contract", as: :customer_checkin_contract, via: [:get, :post]

  # HomeController
    get "/kennel_or_customer", to: "home#kennel_or_customer", as: :kennel_or_customer
    get "/about", to: "home#about", as: :about
    get "/faq", to: "home#faq", as: :faq
    get "/policies_and_terms", to: "home#policies_and_terms", as: :policies_and_terms
    get "/changes_cancellations_refunds", to: "home#changes_cancellations_refunds", as: :changes_cancellations_refunds
    get "/terms_of_service", to: "home#terms_of_service", as: :terms_of_service
    get "/privacy_policy", to: "home#privacy_policy", as: :privacy_policy

  # Contact
    get "/message_confirmation", to: "contact_messages#message_confirmation", as: :message_confirmation


end

app/views/shared/_amenities_modal.html.erb
<div class="modal fade bs-example-modal-lg amenities_container leto_font" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content amenities_div default_white_color">
      <%= form_tag({action: 'new', controller: 'payments'}, method: :get) %>
        <% counter = params[:search_info][:number_of_rooms].to_i %>
        <% params[:search_info][:number_of_rooms].to_i.times do %>
        <div id="room_<%= counter %>_input">
          <p></p>
        </div>
        <% counter -= 1 %>
        <% end %>
        <p></p>
        <input type="hidden" name="kennel_id" value="<%= @searched_kennel[:id] %>">
        <input type="hidden" name="name" value="<%= @searched_kennel[:name] %>">
        <input type="hidden" name="address" value="<%= @searched_kennel[:address] %>">
        <input type="hidden" name="kennel_city" value="<%= @searched_kennel[:city] %>">
        <input type="hidden" name="kennel_state" value="<%= @searched_kennel[:state] %>">
        <input type="hidden" name="kennel_zip" value="<%= @searched_kennel[:zip] %>">
        <input type="hidden" name="kennel_phone" value="<%= @searched_kennel[:phone] %>">
        <input type="hidden" name="kennel_sales_tax" value="<%= @searched_kennel[:sales_tax] %>">
        <input type="hidden" name="kennel_user_email" value="<%= @kennel_user[:email] %>">
        <input type="hidden" name="number_of_nights" value="<%= (params[:search_info][:number_of_nights].to_i) %>">
        <input type="hidden" name="number_of_rooms" value="<%= params[:search_info][:number_of_rooms] %>">
        <input type="hidden" name="number_of_cats" value="<%= params[:search_info][:number_of_cats] %>">
        <input type="hidden" name="number_of_dogs" value="<%= params[:search_info][:number_of_dogs] %>">
        <input type="hidden" name="check_in" value="<%= params[:search_info][:check_in] %>">
        <input type="hidden" name="check_out" value="<%= params[:search_info][:check_out] %>">

        <h3 class="text-center amenities_offered_title">Amenities Offered:</h3>
        <% if @amenities.blank? %>
          <strong class="default_white_color">•No Amenities Offered</strong>
        <% else %>
          <% @amenities.to_a.each do |amenity| %>
            <div class="amenities_individual_div">
              <h6 class="amenity_title default_green_color"><strong>• <%= amenity.title %></strong></h6>
              <p class="default_amenity_description">"<%= amenity.description %>"</p>
              <p class="default_amenity_description amenity_price"><%= check_box_tag "amenities[]", amenity.id %> $<%= amenity.price %></p>
              <%#= select_tag "amenity_id_#{amenity.id}", options_for_select(0..20), class: "amenities_selection_tab" %>
            </div>

            <input type="hidden" name="amenity_title_<%= amenity.id %>" value="<%= amenity.title %>">
            <input type="hidden" name="amenity_description_<%= amenity.id %>" value="<%= amenity.description %>">
            <input type="hidden" name="amenity_price_<%= amenity.id %>" value="<%= amenity.price %>">
          <% end %>
        <% end %>
        <div class="text-center"><%= submit_tag "Continue", class: "btn btn-primary" %></div>
      </div>
    </div>
  </div>

app/views/shared/_before_payment_notification.html.erb
<div class="modal fade before_payment_notification leto_font" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <h4 class="text-center">Conditions</h4>
      <div class="text-left margin_left_1em margin_right_1em">
        <h5><strong>Policies:</strong></h5>
        <p>• <strong>Prepayment:</strong> You'll be charged a prepayment of the total cost of your reservation immediately upon confirming your reservation.</p>
        <p>• <strong>Cancellation / Refunds:</strong> Note that if canceled, modified, or in case of no-show, you will be refunded as per our Cancellation Policy.  Please click <%= link_to "here", policies_and_terms_path %> to view our cancellation/refund policy.</p>
        <p>• <strong>How to cancel:</strong> You can contact us with the information in the confirmation email to cancel your booking.</p>
        <p>• <strong>Taxes and service charges:</strong> Sales tax (where applicable) is included. There are no booking or service fees for using PawBookings.com.</p>
      </div>
      <%= submit_tag "Book Now!", class: "btn btn-success payment_submt_btn text-center" %>
      <br />
      <br />
      <br />
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="container-fluid footer_container">
  <div class="row text-center footer_social_media_row hidden_if_desktop">
    <div class="col-xs-3">
      <a target="_blank" href="https://www.facebook.com/Pawbookingscom-Inc-1846215675643858/"><img class="facebook_btn_footer" src="/assets/facebook_btn.png" /></a>
    </div>
    <div class="col-xs-3">
      <a target="_blank" href="https://twitter.com/pawbookings"><img class="twitter_btn_footer" src="/assets/twitter_btn.png" /></a>
    </div>
    <div class="col-xs-3">
      <a target="_blank" href="https://www.pinterest.com/pawbookingscominc/"><img class="pinterest_btn_footer" src="/assets/pinterest_btn.png" /></a>
    </div>
    <div class="col-xs-3">
      <a target="_blank" href="#"><img class="google_plus_btn_footer" src="/assets/google_plus_btn.png" /></a>
    </div>
  </div>
  <div class="row text-center hidden_if_mobile">
    <br />
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="row footer_social_media_row">
        <div class="col-xs-3">
          <a target="_blank" href="https://www.facebook.com/Pawbookingscom-Inc-1846215675643858/"><img class="facebook_btn_footer" src="/assets/facebook_btn.png" /></a>
        </div>
        <div class="col-xs-3">
          <a target="_blank" href="https://twitter.com/pawbookings"><img class="twitter_btn_footer" src="/assets/twitter_btn.png" /></a>
        </div>
        <div class="col-xs-3">
          <a target="_blank" href="https://www.pinterest.com/pawbookingscominc/"><img class="pinterest_btn_footer" src="/assets/pinterest_btn.png" /></a>
        </div>
        <div class="col-xs-3">
          <a target="_blank" href="#"><img class="google_plus_btn_footer" src="/assets/google_plus_btn.png" /></a>
        </div>
      </div>
    </div>
  </div>
  <div class="row text-center footer_row">
    <div class="col-xs-2 col-md-4"></div>
    <div class="col-xs-4 col-md-2">
      <%= link_to "About", about_path, class: "mobile_footer_description" %>
      <br>
      <%= link_to "Blog", blogs_path, class: "mobile_footer_description" %>
      <br>
      <%= link_to "Contact", new_contact_message_path, class: "mobile_footer_description" %>
    </div>
    <div class="col-xs-4 col-md-2">
      <%= link_to "Press", press_pages_path, class: "mobile_footer_description" %>
      <br>
      <%= link_to "Terms", terms_of_service_path, class: "mobile_footer_description" %>
      <br>
      <%= link_to "Help/FAQ", faq_path, class: "mobile_footer_description" %>
    </div>
  </div>
  <br />
  <div class="row text-center">
    <div class="col-md-4"></div>
    <div class="col-xs-12 col-md-4">
      <span id="siteseal">
        <script async type="text/javascript" src="https://seal.godaddy.com/getSeal?sealID=92MVZYL93rzQoTxklMK2cC3FAr7C2bvYXdgjBhYZqmjRzdMlZszh8rvGB7cE"></script>
      </span>
    </div>
  </div>
  <div class="row text-center footer_bottom_row">
    <div class="col-xs-2 col-md-4"></div>
    <div class="col-xs-2 col-md-2">
      <img class="mobile_footer_desciption footer_logo footer_description_logo" src="/assets/paw.png">
    </div>
    <div class="col-xs-8 col-md-6 text-left">
      <p class="footer_bottom_text">PawBookings.com™ © <%= Time.now.year %></p>
    </div>
  </div>
</div>

app/views/shared/_kennel_dashboard_option_btn_div.html.erb
<% if controller_name == "kennels" && action_name == "kennel_dashboard" %>
  <div class="kennel_dashboard_option_btns_div text-center poppins_font">
    <%= link_to "Accommodations", new_run_path, class: "btn btn-success" %>
    <div class="br_if_desktop"><br /></div>
    <%= link_to "Amenities", new_amenity_path, class: "btn btn-success" %>
    <div class="br_if_desktop"><br /></div>
    <%= link_to "Hours of Operation", edit_hours_of_operation_path(session[:hours_of_operation_id]), class: "btn btn-success" %>
    <div class="br_if_desktop"><br /></div>
    <%= link_to "Holidays", new_holiday_path, class: "btn btn-success" %>
    <div class="br_if_desktop"><br /></div>
    <%= link_to "Policies", new_policy_path, class: "btn btn-success" %>
    <div class="br_if_desktop"><br /></div>
    <%= link_to "Breed Restrictions", new_breed_restriction_path, class: "btn btn-success" %>
    <div class="br_if_desktop"><br /></div>
    
    <%= link_to "Enter Reservation", old_reservation_path, class: "btn btn-success"%>
    <div class="br_if_desktop"><br /></div>
    <%= link_to "Kennel Pictures", new_photo_path, class: "btn btn-success" %>
    <% if @kennel.present? %>
        <p class="default_white_color poppins_font">Link for external pages:</p>
        <textarea rows="5" cols="20"><%= "<a href='#{kennel_url(id: @kennel.friendly_id)}' target='_blank'>Book Now</a>".html_safe %></textarea>
    <% end %>
  </div>
<% else %>
  <div class="text-center kennel_dashboard_option_btns_div_mobile poppins_font">
    <%= link_to "Accommodations", new_run_path, class: "btn btn-success" %>
    <%= link_to "Amenities", new_amenity_path, class: "btn btn-success" %>
    <%= link_to "Hours of Operation", edit_hours_of_operation_path(session[:hours_of_operation_id]), class: "btn btn-success" %>
    <%= link_to "Holidays", new_holiday_path, class: "btn btn-success" %>
    <%= link_to "Policies", new_policy_path, class: "btn btn-success" %>
    <%= link_to "Breed Restrictions", new_breed_restriction_path, class: "btn btn-success" %>
    <%= link_to "Enter Reservation", old_reservation_path, class: "btn btn-success"%>
    <% if @kennel.present? %>
        <p class="default_white_color poppins_font">Link for external pages:</p>
        <textarea rows="5" cols="20"><%= "<a href='#{kennel_url(id: @kennel.friendly_id)}' target='_blank'>Book Now</a>".html_safe %></textarea>
    <% end %>
    <%= link_to "Kennel Pictures", new_photo_path, class: "btn btn-success" %>
  </div>
<% end %>

app/views/shared/_search_bar.html.erb
<%= form_tag({controller: "searches", action: "create"}, {method: "post"}) do %>
  <div class="mobile_search_div">
    <div class="row text-center">
        <div class="col-xs-12">
          <div class="row">
            <div class="col-xs-6">
              <%= label_tag "Zip code", nil, class: "search_label" %>
              <br />
              <%= text_field_tag(:search_zip, nil, placeholder: " Zip Code", class: "common_search_field search_zip", onkeypress: "return isNumber(event);", maxlength: "5", required: true, value: params[:search_zip]) %>
            </div>
            <div class="col-xs-6">
              <%= label_tag "Distance", nil, class: "search_label" %>
              <br />
              <%= text_field_tag(:radius, nil, type: 'number', placeholder: " Distance", class: "common_search_field", onkeypress: "return isNumber(event);", maxlength: "3", max: '100', value: params[:radius]) %>
            </div>
          </div>
        </div>
      </div>

    <div style="margin-top: 1em;" class="row text-center">
      <div class="col-xs-12">
        <%= label_tag "Reservation dates", nil, class: "search_label" %>
        <%= text_field_tag(:reservation_dates, nil, class: "daterange_check_in common_search_field text-center", required: true, name: "reservation_dates", value: params[:reservation_dates]) %>
      </div>
    </div>

    <div style="margin-top: 1em;" class="row text-center">
      <div class="col-xs-6">
        <%= label_tag "Number of Dogs", nil, class: "search_label" %>
        <%= select_tag(:number_of_dogs, options_for_select(number_of_pets_option, params[:number_of_dogs]), class: "form-control common_search_field") %>
      </div>

      <div class="col-xs-6">
        <%= label_tag "Number of cats", nil, class: "search_label" %>
        <%= select_tag(:number_of_cats, options_for_select(number_of_pets_option, params[:number_of_cats]), class: "form-control common_search_field") %>
      </div>
    </div>

    <div style="margin-top: 1em;" class="row text-center">
      <div class="col-xs-12">
        <%= label_tag "Number of rooms", nil, class: "search_label" %>
        <%= select_tag(:number_of_rooms, options_for_select(number_of_rooms_option, params[:number_of_rooms]), class: "form-control common_search_field") %>
      </div>
    </div>

    <div class="row text-center">
      <div class="col-xs-12">
        <%= button_to "Search", "#", class: "search_submit_btn" %>
      </div>
    </div>
  </div>
<% end %>


<script type='text/javascript'>
  $(".search_submit_btn").on("click", function(){
    var search_zip = $("#search_zip").val();
    var radius = $("#radius").val();
    var reservation_dates = $("#reservation_dates").val();
    var number_of_dogs = $("#number_of_dogs").val();
    var number_of_cats = $("#number_of_cats").val();
    var number_of_rooms = $("#number_of_rooms").val();

    // $.ajax({ url: "/searches?", data: my_key_vals, type: "POST" });
    if(search_zip != ""){
      $.redirectPost("/searches", {search_zip: search_zip, radius: radius, reservation_dates: reservation_dates, number_of_dogs: number_of_dogs, number_of_cats: number_of_cats, number_of_rooms: number_of_rooms});
    }
  });

  $.extend(
{
    redirectPost: function(location, args)
    {
        var form = $('<form></form>');
        form.attr("method", "post");
        form.attr("action", location);

        $.each( args, function( key, value ) {
            var field = $('<input></input>');

            field.attr("type", "hidden");
            field.attr("name", key);
            field.attr("value", value);

            form.append(field);
        });
        $(form).appendTo('body').submit();
    }
});


</script>

app/views/shared/_testimonials.html.erb
<div class="container-fluid testimonial_container">
  <div class="row text-center">
    <div class="col-xs-12">
      <h5 class="testimonials_top_text arvo_font">Testimonials</h5>
      <h6 class="testimonials_bottom_text poppins_font">We think we’re the best thing for pet owners and boarding kennels since…. well…. boarding kennels!
      </h6>
      <h6 class="testimonials_bottom_text poppins_font">But don’t just take our word for it. Check out what others have to say about <span style="font-size:1.2em;" class="default_green_color poppins_font">PawBookings.com</span> and some of our Client Kennels.</h6>
    </div>
  </div>

<% if !@testimonials.blank? %>
  <% @testimonials.each do |t| %>
    <div class="testimonial_desktop">
      <div class="row text-center testimonial_row">
        <div class="col-md-3">
          <%= image_tag t[2], class: "testimonial_avatar" %>
          <p class="testimonial_person_name"><%= "#{t[0].capitalize} #{t[1].capitalize}" %></p>
        </div>
        <div class="col-md-9">
          <p class="testimonial_comment">"<%= "#{t[6]}" %>"</p>
          <p class="testimonial_kennel_details"><%= t[3] %></p>
          <p class="testimonial_kennel_details"><%= "#{t[4]}, #{t[5]}" %></p>
        </div>
      </div>
    </div>
  <!--  -->
    <div class="testimonial_mobile">
      <div class="row text-center testimonial_row">
        <div class="col-xs-12">
          <%= image_tag t[2], class: "testimonial_avatar" %>
          <p class="testimonial_person_name"><%= "#{t[0].capitalize} #{t[1].capitalize}" %></p>
          <p class="testimonial_comment">"<%= "#{t[6]}" %>"</p>
          <p class="testimonial_kennel_details"><%= t[3] %></p>
          <p class="testimonial_kennel_details"><%= "#{t[4]}, #{t[5]}" %></p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

</div>

app/views/shared/_top_info.html.erb
<div class="container-fluid top_nav_container">
  <div class="row top_nav_bar_row nav_bar_mobile">
      <div class="col-xs-6">
        <a href="/"><img class="top_logo" src="/assets/pawbookings.png"></a>
      </div>
      <div class="col-xs-6 text-right">
        <span id="mobile_nav_btn" class="glyphicon glyphicon-align-justify top_mobile_glyphicon"></span>
      </div>
  </div>
  <div class="row top_nav_bar_row nav_bar_desktop">
    <div class="col-md-2">
      <a href="/"><img class="top_logo" src="/assets/pawbookings.png"></a>
    </div>
    <div class="col-md-8">
      <ul class="top_info_desktop_nav_ul">
        <li class="top_info_desktop_nav_li"><%= link_to "Home", '/', class:"default_white_color poppins_font" %></li>
        <li class="top_info_desktop_nav_li"><%= link_to "Search", search_results_path(no_params: "true"), class:"default_white_color poppins_font" %></li>
        <li class="top_info_desktop_nav_li"><%= link_to "About", about_path, class:"default_white_color poppins_font" %></li>
        <li class="top_info_desktop_nav_li"><%= link_to "Contact/Support", new_contact_message_path, class:"default_white_color poppins_font" %></li>
        <li class="top_info_desktop_nav_li"><%= link_to "Policies/Terms", policies_and_terms_path, class:"default_white_color poppins_font" %></li>
        <li class="top_info_desktop_nav_li"><%= link_to "FAQ", faq_path, class:"default_white_color poppins_font" %></li>
        <li class="top_info_desktop_nav_li"><%= link_to "Blog", blogs_path, class:"default_white_color poppins_font" %></li>
      </ul>
    </div>
    <div class="col-md-2 text-left">
      <% if current_user.nil? %>
        <h5><a href="<%= new_user_session_path %>"><img class="mobile_login_btn" src="/assets/login_btn.png"></a></h5>
        <h5><a href="<%= kennel_or_customer_path %>"><img class="mobile_signup_btn" src="/assets/signup_btn.png"></a></h5>
      <% else %>
        <div class="welcome_logout_div poppins_font">
          <%= "Welcome, #{current_user.first_name.capitalize}!" %>
          <br />
          <%= link_to("Log out", destroy_user_session_path, class: "mobile_nav_text poppins_font", method: "delete") %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row text-center mobile_nav_menu" id="mobile_nav_menu">
    <div class="col-xs-12">
      <h5><a href="<%= new_user_session_path %>"><img class="mobile_login_btn" src="/assets/login_btn.png"></a></h5>
      <br>
      <h5><a href="<%= kennel_or_customer_path %>"><img class="mobile_signup_btn" src="/assets/signup_btn.png"></a></h5>
      <br>
      <h5><%= link_to "Home", root_path, class: "mobile_nav_text poppins_font" %></h5>
      <br>
      <h5><%= link_to "Search", search_results_path(no_params: "true"), class: "mobile_nav_text poppins_font" %></h5>
      <br>
      <h5><%= link_to "About", about_path, class: "mobile_nav_text poppins_font" %></h5>
      <br>
      <h5><%= link_to "Contact/Support", new_contact_message_path, class: "mobile_nav_text poppins_font" %></h5>
      <br>
      <h5><%= link_to "Policies/Terms", policies_and_terms_path, class: "mobile_nav_text poppins_font" %></h5>
      <br>
      <h5><%= link_to "FAQ", faq_path, class: "mobile_nav_text poppins_font" %></h5>
      <br>
      <h5><%= link_to "Blog", blogs_path, class: "mobile_nav_text poppins_font" %></h5>
      <br>
      <% if !current_user.nil? %>
        <h5><%= link_to("Log out", destroy_user_session_path, class: "mobile_nav_text poppins_font", method: "delete") %></h5>
        <br>
        <br>
      <% end %>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('#flash').delay(500).fadeIn('normal', function() {
    $(this).delay(2500).fadeOut();
  });
</script>

app/views/shared/_user_signup_links.html.erb
<div class="container-fluid">
  <div class="row text-center">
    <% if current_user.nil? %>
      <div class="col-xs-6">
        <%= link_to "Customer Signup", new_user_registration_path(kennel_or_customer: "customer") %>
      </div>
      <div class="col-xs-6">
        <%= link_to "Kennel Signup", new_user_registration_path(kennel_or_customer: "kennel") %>
      </div>
    <% end %>
  </div>
</div>