config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  root to: "home#index"
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { registrations: "devise_registrations", passwords: "devise_passwords" }
  get "/users/sign_in" => redirect("/")

  resources :home
  resources :contact_messages, only: [:new, :create]
  resources :customer_emergency_contacts, only: [:edit, :new, :create, :update, :destroy]
  resources :customer_vet_infos, only: [:edit, :new, :create, :update, :destroy]
  resources :hours_of_operations, only: [:edit, :update, :create, :destroy]
  resources :holidays
  resources :breed_restrictions
  resources :pets, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :amenities, only: [:new, :create, :update, :destroy, :edit]
  resources :policies, only: [:new, :create, :update, :destroy, :edit]
  resources :photos, only: [:new, :create, :update, :destroy, :edit]
  get '/reservations/old', to: "reservations#old_reservations", as: :old_reservation
  get '/get_pets', to: "reservations#get_pets", as: :get_pets

  resources :reservations, only: [:show, :new, :create]
  resources :kennel_ratings, only: [:new, :create]
  resources :stand_by_reservations, only: [:new, :create]
  resources :check_in_check_out_reservations, only: [:update]
  resources :check_in_contract_important_informations, only: [:update, :edit]
  resources :check_in_contract_reservation_changes, only: [:update, :edit]
  resources :check_in_contract_refund_policies, only: [:update, :edit]
  resources :press_pages

  # CsvKennelsController
    resources :csv_kennels
    post '/notify_kennel', to: 'csv_kennels#notify_kennel', as: :notify_kennel
    get '/claim_business', to: 'csv_kennels#claim_business', as: :claim_business
    post '/send_business_claim', to: 'csv_kennels#send_business_claim', as: :send_business_claim


  # PawbookingsAdminsController
   resources :pawbookings_admins, only: [:index]
   get '/admin_reservation_search', to: "pawbookings_admins#admin_reservation_search", as: :admin_reservation_search

   get '/refund_reservation_select', to: "pawbookings_admins#refund_reservation_select", as: :refund_reservation_select
   get '/refund_reservation_confirm', to: "pawbookings_admins#refund_reservation_confirm", as: :refund_reservation_confirm

   get '/update_reservation', to: "pawbookings_admins#update_reservation", as: :update_reservation

  # RunsController
    resources :runs, only: [:new, :create, :update, :destroy, :edit]
    delete "/delete_run_image", to: "runs#delete_run_image", as: :delete_run_image

  # PaymentsController
    resources :payments, only: [:new, :create]
    get "/vaccination_upload_after_payment", to: "payments#vaccination_upload_after_payment", as: :vaccination_upload_after_payment

  # KennelsController
    resources :kennels, only: [:new, :create, :update, :show, :edit, :index, :destroy]
    get "/kennel_dashboard",   to: "kennels#kennel_dashboard",   as: :kennel_dashboard
    get "/kennel_reservations", to: "kennels#kennel_reservations", as: :kennel_reservations
    get "/kennel_view_pets", to: "kennels#kennel_view_pets", as: :kennel_view_pets
    get '/search_reservations', to: "kennels#search_reservations", as: :search_reservations
    match "/kennel_searched_reservation", to: "kennels#kennel_searched_reservation", as: :kennel_searched_reservation, via: [:get, :post]

  # CustomersController
    get "/customer_dashboard", to: "customers#customer_dashboard", as: :customer_dashboard
    post "/create_user_image", to: "customers#create_user_image", as: :create_user_image
    delete "/delete_user_image", to: "customers#delete_user_image", as: :delete_user_image

  # SearchesController
    resources :searches, only: [:create]
    get "/search_results", to: "searches#search_results", as: :search_results

  # BlogsController
    resources :blogs
    match "/blog_search", to: "blogs#blog_search", as: :blog_search, via: [:get, :post]
    get "/all_blogs", to: "blogs#all_blogs", as: :all_blogs

  # BlogCategoriesController
    resources :blog_categories
    get "/all_blog_categories", to: "blog_categories#all_blog_categories", as: :all_blog_categories

  # Contracts
    match "/customer_checkin_contract", to: "contracts#customer_checkin_contract", as: :customer_checkin_contract, via: [:get, :post]

  # HomeController
    get "/kennel_or_customer", to: "home#kennel_or_customer", as: :kennel_or_customer
    get "/about", to: "home#about", as: :about
    get "/faq", to: "home#faq", as: :faq
    get "/policies_and_terms", to: "home#policies_and_terms", as: :policies_and_terms
    get "/changes_cancellations_refunds", to: "home#changes_cancellations_refunds", as: :changes_cancellations_refunds
    get "/terms_of_service", to: "home#terms_of_service", as: :terms_of_service
    get "/privacy_policy", to: "home#privacy_policy", as: :privacy_policy

  # Contact
    get "/message_confirmation", to: "contact_messages#message_confirmation", as: :message_confirmation


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if !current_user.nil? && current_user.kennel_or_customer == "kennel"
       redirect_to kennel_dashboard_path
    elsif !current_user.nil? && current_user.kennel_or_customer == "customer"
       redirect_to customer_dashboard_path
    elsif !current_user.nil? && current_user.kennel_or_customer == "admin"
       redirect_to pawbookings_admins_path
    else
       root_path
    end

    @kennel_ratings = KennelRating.where(rating: 5).last(3).reverse
    testimonials
  end

  def testimonials
    @testimonials = []
    if !@kennel_ratings.blank?
      @kennel_ratings.each do |kr|
        get_user_info(kr)
        get_kennel_info(kr)
        @testimonials << [@user.first_name, @user.last_name, @user.user_image, @kennel.name, @kennel.city, @kennel.state, kr.comment]
      end
    end
  end

  def get_user_info(kennel_rating)
    @user = User.find(kennel_rating.userID)
  end

  def get_kennel_info(kennel_rating)
    @kennel = Kennel.find(kennel_rating.kennelID)
  end

  def kennel_or_customer
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<%= render partial: "shared/top_info" %>

<div class="container-fluid">
  <div class="row text-center">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <h5 class="main_title arvo_font">Who we are...</h5>
      <br />
      <img class="about_image" src="/assets/about_image.jpg">
    </div>
  </div>
  <div class="row text-center">
    <div class="col-xs-12">
      <div class="about_div">
        <h6 class="about_details poppins_font">
        PawBookings.com was founded by an avid pet lover and dog owner whose first job was working at a boarding kennel when he was a kid.  For ten years, the kennel owners, along with the rest of the staff, taught him so much.  He worked in every role at the kennel and learned some life-long lessons about work, responsibility, trust and love.  Patrick’s passion for caring for man’s best friend and our feline companions organically led to the creation of PawBookings.com.
      </h6>
      </div>
      <div class="about_div">
        <h6 class="about_details poppins_font">
        We have built this PawBookings.com website from the ground up, using state-of-the-art development and technology and are now your go-to website for dog and cat kennel boarding throughout the United States.  Gone are the days of searching for the perfect accommodation for your pet using phone books, the web and then calling the Kennel during business hours.  You can search for and book a reservation for your pet all in one website 24/7/365!
      </h6>
      </div>
      <div class="about_div">
        <h6 class="about_details poppins_font">
        We’ve done all the hard work of researching kennels, collecting all their information and offerings.  Now all you do is enter in your location, select the dates you are looking to book and we do all the heavy lifting for you.  PawBookings.com will return boarding kennels in your area, give you information about them along with ratings/reviews and current pricing.  Do this all from the comfort of your home, or on the go via your mobile device anytime of the day or night.
      </h6>
      </div>
      <div class="about_div">
        <h6 class="about_details poppins_font">
        For our Kennel Partners, we free up a significant portion of your staff’s time by automating the kennel reservation process for you.  With our easy to use, yet powerful website, it’s easy to get up and running fast!  Signing up to be a part of our platform is easy!  And with answering a few questions, telling us a little about your business and uploading a few photos of your boarding kennel, we can help increase your kennel occupancy and at the same time providing your pet owners with a website that they love and gives you more time to focus on what you do best….providing a safe, loving, caring environment for the pets entrusted to your care.
      </h6>
      </div>
    </div>
  </div>
</div>
<br />

<%= render partial: "shared/footer" %>

app/views/home/changes_cancellations_refunds.html.erb
<%= render partial: "shared/top_info" %>

<div class="container-fluid">
  <div class="row text-left">
    <div class="col-md-2"></div>
    <div class="col-xs-12 col-md-8">
      <h5 class="main_title text-center arvo_font">Changes - Cancellations - Refunds</h5>
      <div class="border"></div>
      <br />
      <br />
      <h3 class="arvo_font default_green_color">Changes</h3>
      <p class="poppins_font font_1_1_em line_height_1p5">Changes to your reservation must be made by calling our reservation specialists at (888) 840-PAWS / (888) 840-7297. Or you can send an email to reservations@pawbookings.com. All changes to your booking must be made in accordance with our Change/Cancellation/Refund policy. Please note that changes to a reservation may not be possible due to the vacancy/non-vacancy capacity of our Kennel Operators.</p>
      <br />
      <h3 class="arvo_font default_green_color">Cancellations</h3>
      <p class="poppins_font font_1_1_em line_height_1p5">All cancellations must be made by emailing reservations@pawbookings.com or by calling our reservations specialists at (888) 840-PAWS / (888) 840-7297. Due to the time-sensitive nature of our refund policy, it is important to contact us IMMEDIATELY should you need to cancel your reservation. All cancellations are processed and any refunds, if applicable, are in accordance with our Changes/Cancellations/Refund Policy.</p>
      <br />
      <h3 class="arvo_font default_green_color">Refunds</h3>
      <strong>In the event of a Change or Cancellation, PawBookings.com, Inc. will refund your payment in accordance with the following policy, unless otherwise provided by the Kennel Operator.</strong>
      <br />
      <br />
      <p class="poppins_font font_1_1_em line_height_1p5"><span class="default_green_color arvo_font">a</span>. <strong class="arvo_font"> Full Refund</strong>: If you cancel your booking 14 or more days prior to the scheduled drop off date, PawBookings.com, Inc. will refund 100% of your payment.</p>
      <p class="poppins_font font_1_1_em line_height_1p5"><span class="default_green_color arvo_font">b</span>. <strong class="arvo_font"> Partial Refund</strong>: If you cancel your booking less than 14 days, but not less than 7 days prior to the scheduled drop off date, you will be charged a fee equal to 25 % of the reservation total, or a full 1-night stay, whichever is greater. If you cancel your booking less than 7 days, but not less than 3 days prior to the scheduled drop off date, you will be charged a fee equal to 50% of the reservation total, or a full 3-night stay, whichever is greater.</p>
      <p class="poppins_font font_1_1_em line_height_1p5"><span class="default_green_color arvo_font">c</span>. <strong class="arvo_font"> No Refund</strong>: If you cancel your booking less than 3 days prior to your scheduled drop off date, except in unusual circumstances.</p>
      <p class="poppins_font font_1_1_em line_height_1p5"><span class="default_green_color arvo_font">d</span>. <strong class="arvo_font"> Extenuating Circumstances</strong>: Unusual circumstances are handled on a case by case basis. If a problem has arisen requiring action from PawBookings.com, Inc., the Pet Owner User must contact us at support@pawbookings.com within 3 days after the stay has occurred or after the cancellation. Please allow 2-3 weeks for any refunds that take place due to unusual circumstances.</p>
    </div>
  </div>
  <br />
  <br />
  <div class="row text-center">
    <div class="col-md-4"></div>
    <div class="col-xs-12 col-md-4">
      <div class="div_border">
        PawBookings.com, Inc. is under no obligation to intervene in any dispute between Users regarding cancellations and/or refunds outside the scope of our cancellation policy. Other terms may apply and pet owners are responsible for reviewing any individual Kennel Operator's policies regarding cancellation fees.
      </div>
    </div>
  </div>
</div>
<br />
<br />
<br />
<br />
<%= render partial: "shared/footer" %>

app/views/home/index.html.erb
<% set_meta_tags keywords: ["pawbookings", "pet booking", "kennels", "pet hotel", "pet reservation", "local pet kennels", "luxury pet kennels", "high class pet kennels", "kennel reservation software", "online kennel booking", "boarding", "online pet boarding", "kennel with webcams", "24 hour kennels", "find a kennel", "vip kennels", "pet vacation", "pet accommodations"] %>

<%= render partial: "shared/top_info" %>

<div class="container-fluid main_hero_bg">
  <div class="row text-center main_hero_text">
    <div class="col-md-3"></div>
    <div class="col-xs-12 col-md-6">
      <h5 class="top_hero_text arvo_font margin_top_1em margin_bottom_p5em">Find A Boarding Kennel For Your Pet With Ease</h5>
      <h6 class="bottom_hero_text poppins_font">We do all the searching for you. Enter your zip code, the dates for your pet’s holiday, and book it!</h6>
    </div>
  </div>
  <div class="mobile_search_div_home">
    <%= render partial: "shared/search_bar" %>
  </div>
</div>
<div class="border"></div>
<div class="border"></div>

<%= render partial: "shared/why_pawbookings" %>

<% if !@testimonials.blank? %>
  <%= render partial: "shared/testimonials" %>
<% end %>
<div class="border"></div>
<div class="border"></div>
<div class="border"></div>

<%= render partial: "shared/footer" %>

app/views/home/policies_and_terms.html.erb
<%= render partial: "shared/top_info" %>

<div class="container-fluid">
  <div class="row text-center">
    <div class="col-md-2"></div>
    <div class="col-xs-12 col-md-8">
      <h5 class="main_title arvo_font text-center">Policies/Terms</h5>
      <div class="border"></div>
      <br />
      <br />
    </div>
  </div>
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-xs-12 col-md-8">
      <h3 class="arvo_font default_green_color">Changes/Cancellations/Refund Policy</h3>
      <p class="poppins_font font_1_1_em line_height_1p5"><%= truncate("Changes to your reservation must be made by calling our reservation specialists at 1-844-944-3333. Or you can send an email to reservations@pawbookings.com. All changes to your booking must be made in accordance with our Change/Cancellation/Refund policy. Please note that changes to a reservation may not be possible due to the vacancy/non-vacancy capacity of our Kennel Operators.", length: 345, omission: "... ") %><%= link_to "read more", changes_cancellations_refunds_path %></p>
      <br />
      <h3 class="arvo_font default_green_color">Terms of Service</h3>
      <p class="poppins_font font_1_1_em line_height_1p5"><%= truncate('Welcome to the PawBookings.com, Inc. ("PawBookings.com, Inc.") service (the "Service"). The following Terms of Service govern all use of the Service via the website located at www.pawbookings.com including, but not limited to, researching and gathering data from pet boarding kennels and other pet service and product providers; making reservations; and all content, services, and products available at or through the Website. Any use of the site/service for purposes other than intended is strictly prohibited.', length: 345, omission: "... ") %><%= link_to "read more", terms_of_service_path %></p>
      <br />
      <h3 class="arvo_font default_green_color">Privacy Policy</h3>
      <p class="poppins_font font_1_1_em line_height_1p5"><%= truncate('This privacy policy (Policy) sets out how PawBookings.com uses and protects any information that you give PawBookings.com when you use this website. PawBookings.com is committed to ensuring that your privacy is protected. In the event you are asked to provide personal information when using this website, then you can be assured that it will only be used in accordance with this privacy statement. PawBookings.com may change this policy from time to time by updating this page.', length: 345, omission: "... ") %><%= link_to "read more", privacy_policy_path %></p>
      <br />
    </div>
  </div>
</div>

<br />
<br />
<br />
<%= render partial: "shared/footer" %>

app/views/home/privacy_policy.html.erb
<%= render partial: "shared/top_info" %>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-xs-12 col-md-8">
      <h5 class="main_title arvo_font text-center">Privacy Policy</h5>
      <div class="border"></div>
      <br />
      <p class="poppins_font font_italic">This policy has been updated and is effective from 11/01/2016.</p>
      <br />
      <p class="poppins_font font_1_1_em line_height_1p5">This privacy policy (Policy) sets out how PawBookings.com uses and protects any information that you give PawBookings.com when you use this website.</p>
      <p class="poppins_font font_1_1_em line_height_1p5">PawBookings.com is committed to ensuring that your privacy is protected. In the event you are asked to provide personal information when using this website, then you can be assured that it will only be used in accordance with this privacy statement. PawBookings.com may change this policy from time to time by updating this page.</p>
      <p class="poppins_font font_1_1_em line_height_1p5">We pledge to you, our customer, that we have made a dedicated effort to bring our privacy policy in line with all relevant and important privacy laws and initiatives.</p>
      <br />
      <ol class="margin_top_np5em">
        <strong><li>Security</li></strong>
        <br />
        <p class="poppins_font margin_top_np5em">We are committed to ensuring that your information is secure. To prevent unauthorized access or disclosure, we have put in place suitable physical, electronic and managerial procedures to safeguard and secure the information we collect online.</p>
        <br />
        <strong><li>Do We Use Cookies?</li></strong>
        <br />
        <p class="poppins_font margin_top_np5em">Yes (Cookies are small files that a site or its service provider transfers to your computer’s hard drive through your Web browser (if you allow) that enables the sites or service providers’ systems to recognize your browser and capture and remember certain information.</p>
        <br />
        <strong><li>How We Use Cookies</li></strong>
        <br />
        <p class="poppins_font margin_top_np5em">A cookie is a small file which asks permission to be placed on your computer’s hard drive. Once you agree, the file is added and the cookie helps analyze web traffic or lets you know when you visit a particular site. Cookies allow web applications to respond to you as an individual. The web application can tailor its operations to your needs, likes and dislikes by gathering and remembering information about your preferences. We use traffic log cookies to identify which pages are being used. This helps us analyze data about web page traffic and improve our website in order to tailor it to customer needs. We only use this information for statistical analysis purposes and then the data is removed from the system. Overall, cookies help us provide you with a better website, by enabling us to monitor which pages you find useful and which you do not. A cookie in no way gives us access to your computer or any information about you, other than the data you choose to share with us. You can choose to accept or decline cookies. Most web browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies if you prefer. This may prevent you from taking full advantage of the website. Persistent cookies enable us to track and target the interests of our users to enhance the experience on our site. Third party vendors, including Google, show our ads on sites on the internet. Third party vendors, including Google, use our cookies to serve PawBookings.com ads based on a user’s prior visits to our website. Users may opt out of Google’s use of cookies by visiting the Google advertising opt-out page. (Alternatively you can opt out of a third-party vendor’s use of our cookies by visiting the Network Advertising Initiative opt out page.)</p>
        <br />
        <strong><li>How To Opt Out?</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">If you no longer want to be exposed to Interview Master System personalized banners, you can opt out by simply visiting the Network Advertising Initiative website: httpa://www.networkadvertising.org/managing/opt_out.asp.</p>
        <p class="poppins_font line_height_1p5 font_1_1_em line_height_1p5">Please note: This procedure will not block ads that are displayed on the websites you visit.</p>
        <p class="poppins_font line_height_1p5 font_1_1_em line_height_1p5">Please note: This opt out relies on a cookie, so if you wipe all your cookies then we will no longer know that you have opted out.</p>
        <p class="poppins_font line_height_1p5 font_1_1_em line_height_1p5">Please note: when you opt-out in this manner, a cookie will be set on your browser. We must maintain the cookie on your browser in order to recognize you as an opted-out visitor. You must opt-out again if you clear that cookie from your browser, use a different internet browser, or use a new computer to access the internet.</p>
        <br />
        <strong><li>Links To Other Websites</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">Our website may contain links to other websites of interest. However, once you have used these links to leave our site, you should note that we do not have any control over that other website. Therefore, we cannot be responsible for the protection and privacy of any information which you provide whilst visiting such sites and such sites are not governed by this privacy statement. You should exercise caution and look at the privacy statement applicable to the website in question.</p>
        <br />
        <strong><li>Controlling Your Personal Information</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">You may choose to restrict the collection or use of your personal information in the following ways:</p>
        <p class="poppins_font line_height_1p5 margin_top_np5em">Simply unsubscribe from our newsletter.</p>
        <p class="poppins_font line_height_1p5 margin_top_np5em">If you have previously agreed to have us use your personal information for direct marketing purposes, you may change your mind at any time by writing to or emailing us at support@PawBookings.com</p>
        <br />
        <strong><li>What Information Do We Collect?</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">We collect information from you when you place an order or subscribe to our newsletter. Any data we request that is not required will be specified as voluntary or optional. When ordering or registering on our site, as appropriate, you may be asked to enter your: name, e-mail address, mailing address or credit card information. Like most websites, we use cookies to enhance your experience, gather general visitor information, and track visits to our website. Please refer to the 'do we use cookies?' section for information about cookies and how we use them.</p>
        <br />
        <strong><li>What Do We Use Your Information For?</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">Any of the information we collect from you may be used in one of the following ways:</p>
        <ul>
          <li>To personalize your experience (your information helps us to better respond to your individual needs)</li>
          <br />
          <li>To improve our website (we continually strive to improve our website offerings based on the information and feedback we receive from you)</li>
          <br />
          <li>To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs)</li>
          <br />
          <li>To process transactions Your information, whether public or private, will not be sold, exchanged, transferred, or given to any other company for any reason whatsoever, without your consent, other than for the express purpose of delivering the purchased product or service requested by the customer.</li>
          <br />
          <li>To send periodic emails The email address you provide for order processing, may be used to send you information and updates pertaining to your order or request, in addition to receiving occasional company news, updates, promotions, related product or service information, etc.</li>
          <br />
        </ul>
        <br />
        <strong><li>How Do We Protect Your Information?</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">We implement a variety of security measures to maintain the safety of your personal information when you place an order. These security measures include: password protected directories and databases to safeguard your information, SSL (Secure Sockets Layered) technology to ensure that your information is fully encrypted and sent across the Internet securely or PCI Scanning to actively protect our servers from hackers and other vulnerabilities. We offer the use of a secure server. All supplied sensitive/credit information is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database only to be accessible by those authorized with special access rights to such systems, and are required to keep the information confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) will not be stored on our servers.</p>
        <br />
        <strong><li>Do We Disclose Any Information To Outside Parties?</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">We do not sell, trade, or otherwise transfer to outside parties your personally identifiable information. This does not include trusted third parties who assist us in operating our website, conducting our business, or servicing you, so long as those parties agree to keep this information confidential. We may also release your information when we believe release is appropriate to comply with the law, enforce our site policies, or protect ours or others' rights, property, or safety. However, non-personally identifiable visitor information may be provided to other parties for marketing, advertising, or other uses.</p>
        <br />
        <strong><li>Third Party Links</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">Occasionally, at our discretion, we may include or offer third party products or services on our website. These third party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.</p>
        <br />
        <strong><li>Children Online Privacy Protection Act Compliance</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">We follow the requirements of COPPA (Childrens Online Privacy Protection Act). We do not collect any personal information from anyone under 13 years of age. Our website, products and services are all directed to people who are at least 13 years old or older.</p>
        <br />
        <strong><li>CAN-SPAM Compliance</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">We have taken the necessary steps to ensure that we are compliant with the CAN-SPAM Act of 2003 by never sending out misleading information.</p>
        <br />
        <strong><li>Online Privacy Policy Only</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">This online privacy policy applies only to information collected through our website and not to information collected offline.</p>
        <br />
        <strong><li>Your Consent</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">By using our site, you consent to our privacy policy.</p>
        <br />
        <strong><li>Changes To Our Privacy Policy</li></strong>
        <br />
        <p class="poppins_font line_height_1p5 margin_top_np5em">If we decide to change our privacy policy, we will post those changes on this page, and/or update the Privacy Policy modification date below. Policy changes will apply only to information collected after the date of the change. This policy was last modified on 11/1/16.</p>
        <br />
        <h4 class="poppins_font line_height_1p5 margin_top_np5em">If there are any other questions regarding this privacy policy you may contact us by clicking on the link <%= link_to "here", new_contact_message_path %>.</h4>
      </ol>
    </div>
  </div>
</div>
<br />
<br />

<%= render partial: "shared/footer" %>