config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  root to: "home#index"
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { registrations: "devise_registrations", passwords: "devise_passwords" }
  get "/users/sign_in" => redirect("/")

  resources :home
  resources :contact_messages, only: [:new, :create]
  resources :customer_emergency_contacts, only: [:edit, :new, :create, :update, :destroy]
  resources :customer_vet_infos, only: [:edit, :new, :create, :update, :destroy]
  resources :hours_of_operations, only: [:edit, :update, :create, :destroy]
  resources :holidays
  resources :breed_restrictions
  resources :pets, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :amenities, only: [:new, :create, :update, :destroy, :edit]
  resources :policies, only: [:new, :create, :update, :destroy, :edit]
  resources :photos, only: [:new, :create, :update, :destroy, :edit]
  get '/reservations/old', to: "reservations#old_reservations", as: :old_reservation
  get '/get_pets', to: "reservations#get_pets", as: :get_pets

  resources :reservations, only: [:show, :new, :create]
  resources :kennel_ratings, only: [:new, :create]
  resources :stand_by_reservations, only: [:new, :create]
  resources :check_in_check_out_reservations, only: [:update]
  resources :check_in_contract_important_informations, only: [:update, :edit]
  resources :check_in_contract_reservation_changes, only: [:update, :edit]
  resources :check_in_contract_refund_policies, only: [:update, :edit]
  resources :press_pages

  # CsvKennelsController
    resources :csv_kennels
    post '/notify_kennel', to: 'csv_kennels#notify_kennel', as: :notify_kennel
    get '/claim_business', to: 'csv_kennels#claim_business', as: :claim_business
    post '/send_business_claim', to: 'csv_kennels#send_business_claim', as: :send_business_claim


  # PawbookingsAdminsController
   resources :pawbookings_admins, only: [:index]
   get '/admin_reservation_search', to: "pawbookings_admins#admin_reservation_search", as: :admin_reservation_search

   get '/refund_reservation_select', to: "pawbookings_admins#refund_reservation_select", as: :refund_reservation_select
   get '/refund_reservation_confirm', to: "pawbookings_admins#refund_reservation_confirm", as: :refund_reservation_confirm

   get '/update_reservation', to: "pawbookings_admins#update_reservation", as: :update_reservation

  # RunsController
    resources :runs, only: [:new, :create, :update, :destroy, :edit]
    delete "/delete_run_image", to: "runs#delete_run_image", as: :delete_run_image

  # PaymentsController
    resources :payments, only: [:new, :create]
    get "/vaccination_upload_after_payment", to: "payments#vaccination_upload_after_payment", as: :vaccination_upload_after_payment

  # KennelsController
    resources :kennels, only: [:new, :create, :update, :show, :edit, :index, :destroy]
    get "/kennel_dashboard",   to: "kennels#kennel_dashboard",   as: :kennel_dashboard
    get "/kennel_reservations", to: "kennels#kennel_reservations", as: :kennel_reservations
    get "/kennel_view_pets", to: "kennels#kennel_view_pets", as: :kennel_view_pets
    get '/search_reservations', to: "kennels#search_reservations", as: :search_reservations
    match "/kennel_searched_reservation", to: "kennels#kennel_searched_reservation", as: :kennel_searched_reservation, via: [:get, :post]

  # CustomersController
    get "/customer_dashboard", to: "customers#customer_dashboard", as: :customer_dashboard
    post "/create_user_image", to: "customers#create_user_image", as: :create_user_image
    delete "/delete_user_image", to: "customers#delete_user_image", as: :delete_user_image

  # SearchesController
    resources :searches, only: [:create]
    get "/search_results", to: "searches#search_results", as: :search_results

  # BlogsController
    resources :blogs
    match "/blog_search", to: "blogs#blog_search", as: :blog_search, via: [:get, :post]
    get "/all_blogs", to: "blogs#all_blogs", as: :all_blogs

  # BlogCategoriesController
    resources :blog_categories
    get "/all_blog_categories", to: "blog_categories#all_blog_categories", as: :all_blog_categories

  # Contracts
    match "/customer_checkin_contract", to: "contracts#customer_checkin_contract", as: :customer_checkin_contract, via: [:get, :post]

  # HomeController
    get "/kennel_or_customer", to: "home#kennel_or_customer", as: :kennel_or_customer
    get "/about", to: "home#about", as: :about
    get "/faq", to: "home#faq", as: :faq
    get "/policies_and_terms", to: "home#policies_and_terms", as: :policies_and_terms
    get "/changes_cancellations_refunds", to: "home#changes_cancellations_refunds", as: :changes_cancellations_refunds
    get "/terms_of_service", to: "home#terms_of_service", as: :terms_of_service
    get "/privacy_policy", to: "home#privacy_policy", as: :privacy_policy

  # Contact
    get "/message_confirmation", to: "contact_messages#message_confirmation", as: :message_confirmation


end

app/models/kennel.rb
class Kennel < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  def should_generate_new_friendly_id?
    name_changed?
  end

  belongs_to :user
  has_one    :kennel_check_in_check_out
  has_one    :hours_of_operation
  has_many   :breed_restrictions
  has_many   :holidays
  has_many   :runs
  has_many   :amenities
  has_many   :policies
  has_many   :photos
  has_many   :reservations
  has_many   :stand_by_reservations
  has_many   :users, through: :reservations

  validates :name, presence: true
  validates :address, length: { minimum: 3 }
  validates :mission_statement, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, format: { with: /\A[0-9]{5}\z/i }
  validates :phone, format: { with: /\A\+?[0-9]{,2}(-|\s)?\(?[0-9]{3}\)?(-|\s)?[0-9]{3}(-|\s)?[0-9]{4}\z/ }
  validates :email, uniqueness: true
  validates :cats_or_dogs, presence: true
  validates :avatar, presence: true
  validates :sales_tax, presence: {message: "Must be an integer or decimal value."}

  geocoded_by :zip
  after_validation :geocode, if: ->(obj){ obj.zip.present? and obj.zip_changed? }

  has_attached_file :avatar,
                :storage => :s3,
                styles: { small: "350x333#" }, default_url: "/assets/default_photo_image.png",
                :s3_permissions => { :original => :private, :export => {:quality => 100} },
                :convert_options => { :all => "-quality 100" },
                url: ":s3_domain_url",
                path: "/image/:id/:filename",
                s3_region: ENV["aws_region"],
                :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  def s3_credentials
    {:bucket => ENV["aws_bucket"], :access_key_id => ENV["aws_access_key_id"], :secret_access_key => ENV["aws_secret_access_key"]}
  end

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ApplicationRecord
  has_one  :kennel
  has_one  :customer_vet_info
  has_one  :customer_emergency_contact
  has_many :visits
  has_many :photos
  has_many :pets
  has_many :reservations
  has_many :kennels, through: :reservations
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone, presence: true

  has_attached_file :user_image,
               :storage => :s3,
               styles: { small: "350x333#" }, default_url: "/assets/default_photo_image.png",
               :s3_permissions => { :original => :private, :export => {:quality => 100} },
               :convert_options => { :all => "-quality 100" },
               url: ":s3_domain_url",
               path: "/image/:id/:filename",
               s3_region: ENV["aws_region"],
               :s3_credentials => Proc.new{|a| a.instance.s3_credentials }

  def s3_credentials
   {:bucket => ENV["aws_bucket"], :access_key_id => ENV["aws_access_key_id"], :secret_access_key => ENV["aws_secret_access_key"]}
  end
  validates_attachment_content_type :user_image, content_type: /\Aimage\/.*\Z/
end

app/helpers/kennels_helper.rb
module KennelsHelper
    def states_options
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end

  def time_option
    [
      ['6:00 a.m', '6:00 a.m'],
      ['7:00 a.m', '7:00 a.m'],
      ['8:00 a.m', '8:00 a.m'],
      ['9:00 a.m', '9:00 a.m'],
      ['10:00 a.m', '10:00 a.m'],
      ['11:00 a.m', '11:00 a.m'],
      ['12:00 p.m', '12:00 p.m'],
      ['1:00 p.m', '1:00 p.m'],
      ['2:00 p.m', '2:00 p.m'],
      ['3:00 p.m', '3:00 p.m'],
      ['4:00 p.m', '4:00 p.m'],
    ]
  end

  def unsanitize_date(param)
    @new_date = []
    split_params = param.split('-')
    @new_date << split_params[1]
    @new_date << split_params[2]
    @new_date << split_params[0]
    @new_date = @new_date.join("/")
  end

  def get_kennel_price_range(kennel_id)
    price_range = []
    runs = Run.where(kennel_id: kennel_id).to_a
    runs.each do |run|
      price_range << run[:price]
    end
    @price_range = price_range.sort!
  end

end

app/views/kennels/_kennel_reservations.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" onclick="changeTdHovers();">x</button>
</div>
<div class="modal-body" style="height: auto; margin-top:0 !important; background-color: white; float: none;
    text-align : center;">
    <table class="kennel_reservation_customer_table">
      <% @current_reservations.each_with_index do |res, ind|%>
            <tr style="height: 50px;">
              <th style="border: none; text-align: center;">Res-ID</th>
              <th style="border: none; text-align: center;">Picture</th>
              <th style="border: none; text-align: center;">First Name</th>
              <th style="border: none; text-align: center;">Last Name</th>
              <th style="border: none; text-align: center;">Email</th>
              <th style="border: none; text-align: center;">Phone</th>
              <th style="border: none; text-align: center;">Room Details</th>
              <th style="border: none; text-align: center;">Amenities</th>
              <th style="border: none; text-align: center;">Check-In</th>
              <th style="border: none; text-align: center;">Check-Out</th>
              <th style="border: none; text-align: center;">Total</th>
            </tr>
            <tr style="background-color: #C4C4C4;">

              <td class="kennel_reservation_td vertical_center"><%= res[:id] %></td>
              <% user = User.find(res[:user_id]) %>
              <td class="kennel_reservation_td vertical_center"><%= image_tag user.user_image.url(:thumb), class: "kennel_dashboard_avatar", style: 'margin-top: 20px; margin-right: 0px;' if !user.user_image.url.nil? %></td>
              <td class="kennel_reservation_td vertical_center"><%= res[:customer_first_name].capitalize %></td>
              <td class="kennel_reservation_td vertical_center"><%= res[:customer_last_name].capitalize %></td>
              <td class="kennel_reservation_td vertical_center"><%= res[:customer_email].capitalize %></td>
              <td class="kennel_reservation_td vertical_center"><%= number_to_phone(res[:customer_phone], area_code: true) %></td>
              <% JSON.parse(res[:room_details]).each do |title, price| %>
                <td class="kennel_reservation_td vertical_center">
                  <%= "#{title}" %>
                </td>
              <% end %>
              <% if res[:amenity_details] == '' %>
                <td class="kennel_reservation_td vertical_center">
                  -
                </td>
              <% else %>
                <% hash = JSON.parse(res[:amenity_details]) rescue {}%>
                <% hash.each do |title, description, price, quantity| %>
                  <td class="kennel_reservation_td vertical_center">
                    <%= "#{title}" %>
                    <br />
                    <br />
                  </td>
                <% end %>
              <% end %>
              <td class="kennel_reservation_td vertical_center"><%= unsanitize_date(res[:check_in_date].to_s) %></td>
              <td class="kennel_reservation_td vertical_center"><%= unsanitize_date(res[:check_out_date].to_s) %></td>
              <td class="kennel_reservation_td vertical_center"><%= "$#{res[:total_price]}" %></td>
            </tr>

          </table>
          <p class="kennel_info_p" style="padding-top: 30px; font-size: 24px !important;">Pets</p>
          <br />
          <br />
          <table class="kennel_reservation_customer_table">
            <tr>
                <th style="border: none; text-align: center;">Picture</th>
                <th style="border: none; text-align: center;">Name</th>
                <th style="border: none; text-align: center;">Type</th>
                <th style="border: none; text-align: center;">Breed</th>
                <th style="border: none; text-align: center;">Weight</th>
                <th style="border: none; text-align: center;">Spay or Neutered</th>
                <th style="border: none; text-align: center;">Vaccinations</th>
                <th style="border: none; text-align: center;">Special Instructions</th>
            </tr>
            <% eval(res.pet_ids).each do |pet_id| %>
              <% if !Pet.find_by(id: pet_id).nil? %>
                <% pet = Pet.find(pet_id) %>
                <tr style="background-color: #C4C4C4;" >
                  <td class="kennel_reservation_td vertical_center"><%= image_tag pet.avatar.url(:thumb), class: "kennel_dashboard_avatar", style: 'margin-top: 20px; margin-right: 0px;' if !pet.avatar.url.nil? %></td>
                  <td class="kennel_reservation_td vertical_center"><%= pet[:name].capitalize %></td>
                  <td class="kennel_reservation_td vertical_center"><%= pet[:cat_or_dog].capitalize %></td>
                  <td class="kennel_reservation_td vertical_center"><%= pet[:breed] %></td>
                  <td class="kennel_reservation_td vertical_center"><%= pet[:weight] %> lbs</td>
                  <td class="kennel_reservation_td vertical_center"><%= pet[:spay_or_neutered].capitalize %></td>
                  <% if pet[:vaccinations] == "true" %>
                    <% if pet[:vaccination_record_file_name].nil? %>
                      <td class="kennel_reservation_td vertical_center">Did not upload record</td>
                    <% else %>
                      <td class="kennel_reservation_td vertical_center"><%= link_to "#{pet[:vaccination_record_file_name]}", pet.vaccination_record.url, style: 'color: #0000FF;' %></td>
                    <% end %>
                  <% else %>
                    <td class="kennel_reservation_td vertical_center"><strong>False</strong></td>
                  <% end %>
                  <% if pet[:special_instructions].blank? %>
                    <td class="kennel_reservation_td vertical_center"><strong>n/a</strong></td>
                  <% else %>
                    <td class="kennel_reservation_td vertical_center"><%= pet[:special_instructions] %></td>
                  <% end %>
                <% end %>
          <% end %>
           </tr>
          </table>
          <% end %>
</div>

<script>
$('.day').hover = function() {
  console.log('<%= @current_reservations[0][:amenity_details].nil?%>')
  if ($('#modal-window3').hasClass( "in" )) {
    console.log(this, 'in')
    $(this).addClass('nohover');
  } else {
    console.log(this, 'out')
    $(this).removeClass('nohover');
  }
  
}
</script>

app/views/kennels/kennel_searched_reservation.html.erb
<%= render partial: "shared/top_info" %>
<body class="kennel_reservations_body">
  <div class="container-fluid searched_res_container_desktop">
    <div class="searched_res_desktop">
      <div class="row">
        <div class="col-md-12">
          <h5 class="main_title arvo_font text_underline text-center">ReservationID: <%= @reservation[:id] %></h5>
          <br />
          <br />
          <table class="kennel_reservation_customer_table">
            <caption class="text-center default_green_color">
              <strong class="text_underline">Customer Info:</strong>
            </caption>
            <tr>
              <th class="kennel_reservation_th default_green_color">Res-ID</th>
              <th class="kennel_reservation_th default_green_color">Picture</th>
              <th class="kennel_reservation_th default_green_color">First Name</th>
              <th class="kennel_reservation_th default_green_color">Last Name</th>
              <th class="kennel_reservation_th default_green_color">Email</th>
              <th class="kennel_reservation_th default_green_color">Phone</th>
              <th class="kennel_reservation_th default_green_color">Room Details</th>
              <th class="kennel_reservation_th default_green_color">Amenities</th>
              <th class="kennel_reservation_th default_green_color">Check-In</th>
              <th class="kennel_reservation_th default_green_color">Check-Out</th>
              <th class="kennel_reservation_th default_green_color">Total</th>
            </tr>
            <tr>

              <td class="kennel_reservation_td"><%= @reservation[:id] %></td>
              <% user = User.find(@reservation[:user_id]) %>
              <td class="kennel_reservation_td"><%= image_tag user.user_image.url(:thumb), class: "kennel_dashboard_avatar" if !user.user_image.url.nil? %></td>
              <td class="kennel_reservation_td"><%= @reservation[:customer_first_name].capitalize %></td>
              <td class="kennel_reservation_td"><%= @reservation[:customer_last_name].capitalize %></td>
              <td class="kennel_reservation_td"><%= @reservation[:customer_email].capitalize %></td>
              <td class="kennel_reservation_td"><%= @reservation[:customer_phone] %></td>
              <% JSON.parse(@reservation[:room_details]).each do |title, price| %>
                <td class="kennel_reservation_td">
                  <p><%= "#{title} - $#{price}" %></p>
                </td>
              <% end %>
              <% if @reservation[:amenity_details].nil? %>
                <td class="kennel_reservation_td">
                  <strong class="default_white_color">•No Amenities Chosen.</strong>
                </td>
              <% else %>
                <% JSON.parse(@reservation[:amenity_details]).each do |title, description, price, quantity| %>
                  <td class="kennel_reservation_td">
                    <%= "#{title} - #{description} - $#{price} x #{quantity}" %>
                    <br />
                    <br />
                  </td>
                <% end %>
              <% end %>
              <td class="kennel_reservation_td"><%= unsanitize_date(@reservation[:check_in_date].to_s) %></td>
              <td class="kennel_reservation_td"><%= unsanitize_date(@reservation[:check_out_date].to_s) %></td>
              <td class="kennel_reservation_td"><%= "$#{@reservation[:total_price]}" %></td>
            </tr>
          </table>
          <br />
          <br />
          <% @pets.each do |pet| %>
            <table class="kennel_reservation_customer_table">
              <caption class="text-center default_green_color">
                <strong class="text_underline">Pet#<%= @counter %>:</strong>
              </caption>
              <tr>
                <th class="kennel_reservation_th default_green_color">Picture</th>
                <th class="kennel_reservation_th default_green_color">Name</th>
                <th class="kennel_reservation_th default_green_color">Type</th>
                <th class="kennel_reservation_th default_green_color">Breed</th>
                <th class="kennel_reservation_th default_green_color">Weight</th>
                <th class="kennel_reservation_th default_green_color">Spay or Neutered</th>
                <th class="kennel_reservation_th default_green_color">Vaccinations</th>
                <th class="kennel_reservation_th default_green_color">Special Instructions</th>
              </tr>
              <tr>
                <td class="kennel_reservation_td"><%= image_tag pet.avatar.url(:thumb), class: "kennel_dashboard_avatar" if !pet.avatar.url.nil? %></td>
                <td class="kennel_reservation_td"><%= pet[:name].capitalize %></td>
                <td class="kennel_reservation_td"><%= pet[:cat_or_dog].capitalize %></td>
                <td class="kennel_reservation_td"><%= pet[:breed] %></td>
                <td class="kennel_reservation_td"><%= pet[:weight] %> lbs</td>
                <td class="kennel_reservation_td"><%= pet[:spay_or_neutered].capitalize %></td>
                <% if pet[:vaccinations] == "true" %>
                  <% if pet[:vaccination_record_file_name].nil? %>
                    <td class="kennel_reservation_td"><strong>•Did not upload record</strong></td>
                  <% else %>
                    <td class="kennel_reservation_td"><%= link_to "#{pet[:vaccination_record_file_name]}", pet.vaccination_record.url %></td>
                  <% end %>
                <% else %>
                  <td class="kennel_reservation_td"><strong>False</strong></td>
                <% end %>
                <% if pet[:special_instructions].blank? %>
                  <td class="kennel_reservation_td"><strong>n/a</strong></td>
                <% else %>
                  <td class="kennel_reservation_td"><%= pet[:special_instructions] %></td>
                <% end %>
              </tr>
            </table>
            <br />
            <br />
            <% @counter -= 1 %>
          <% end %>
        </div>
      </div>
    </div>


  <!--  -->


    <div class="searched_res_mobile">
      <div class="row text-center">
        <div class="col-xs-12">
          <h5 class="main_title arvo_font text_underline text-center">ReservationID: <%= @reservation[:id] %></h5>
          <!-- <div class="searched_res_check_in_and_out_div"> -->
            <!-- <div class="border"></div> -->
            <!-- <br> -->
            <!-- <h4 class="default_green_color">Customer Check-In/Check-Out</h4> -->
            <!-- <br /> -->
            <%#= link_to "Customer contract for Check-In", customer_checkin_contract_path(reservation_id: @reservation[:id], user_id: @reservation[:user_id], customer_first_name: @reservation[:customer_first_name], customer_last_name: @reservation[:customer_last_name], check_in_date: @reservation[:check_in_date], check_out_date: @reservation[:check_out_date], customer_email: @reservation[:customer_email], customer_phone: @reservation[:customer_phone], room_details: @reservation[:room_details], run_ids: @reservation[:run_ids], total_price: @reservation[:total_price], kennel_address: params[:kennel_info][:address], kennel_city: params[:kennel_info][:city], kennel_state: params[:kennel_info][:state], kennel_zip: params[:kennel_info][:zip], kennel_email: params[:kennel_info][:email], kennel_phone: params[:kennel_info][:phone], kennel_name: params[:kennel_info][:name], pets: @pet_ids.to_s, format: :pdf), target: '_blank', class:"btn btn-primary" %>
            <!-- <br> -->
            <!-- <br> -->
            <%# if @reservation[:checked_in] == "true" %>
              <!-- <p style="color:green">√ This user has been marked as checked-in. <%#= link_to "revert?", check_in_check_out_reservation_path(checked_in: "false", id: @reservation[:id]), method: :put %></p> -->
            <%# else %>
              <%#= button_to "Check-In this customer", check_in_check_out_reservation_path(checked_in: "true", id: @reservation[:id]), method: :put, class:"btn btn-primary" %>
            <%# end %>
            <!-- <br> -->
            <%# if @reservation[:checked_out] == "true" %>
             <!--  <p style="color:green">√ This user has been marked as checked-out. <%#= link_to "revert?", check_in_check_out_reservation_path(checked_out: "false", id: @reservation[:id]), method: :put %></p> -->
            <%# else %>
              <%#= button_to "Check-Out this customer", check_in_check_out_reservation_path(checked_out: "true", id: @reservation[:id]), method: :put, class:"btn btn-primary" %>
            <%# end %>
            <!-- <br /> -->
            <!-- <br /> -->
            <!-- <div class="border"></div> -->
          <!-- </div> -->

          <div class="searched_res_customer_info_div">
            <h4 class="default_green_color">Customer Info</h4>
            <br />
            <p><strong>First Name: </strong><%= @reservation[:customer_first_name] %></p>
            <p><strong>Last Name: </strong><%= @reservation[:customer_last_name] %></p>
            <p><strong>Email: </strong><%= @reservation[:customer_email] %></p>
            <p><strong>Phone: </strong><%= @reservation[:customer_phone] %></p>
            <br />
          </div>
          <div class="border"></div>
          <div class="searched_res_rooms_chosen_div">
            <br />
            <h4 class="default_green_color">Rooms Details</h4>
            <br />
            <% JSON.parse(@reservation[:room_details]).each do |room_name, room_price| %>
            <strong>•<%= room_name %>- $<%= room_price %></strong>
            <br>
            <br>
            <% end %>
          </div>
          <br />
          <div class="border"></div>
          <div class="searched_res_check_in_and_out_dates_div">
            <br />
            <h4 class="default_green_color">Check-in/Check-out Dates</h4>
            <br />
            <strong>Check-In: </strong>
            <br />
            <strong><h5><%= unsanitize_date(@reservation[:check_in_date].to_s) %></h5></strong>
            <br>
            <strong>Check-Out: </strong>
            <br />
            <h5><%= unsanitize_date(@reservation[:check_out_date].to_s) %></h5>
          </div>
          <br />
          <div class="border"></div>
          <div class="searched_res_pets_chosen_div">
            <br />
            <h4 class="default_green_color">Pets Chosen</h4>
            <br />
            <% counter = @pets.length %>
            <% @pets.each do |pet| %>
              <h5 class="default_green_color">Pet #<%= counter %></h5>
              <p><strong>Name: </strong><%= pet[:name] %></p>
              <p><strong>Cat or Dog: </strong><%= pet[:cat_or_dog] %></p>
              <p><strong>Breed: </strong><%= pet[:breed] %></p>
              <p><strong>Weight: </strong><%= pet[:weight] %></p>
              <p><strong>Vaccincated: </strong><%= pet[:vaccinations] %></p>
              <p><strong>Spay or Neutered: </strong><%= pet[:spay_or_neutered] %></p>
              <br>
              <% counter -= 1 %>
            <% end %>
          </div>
          <br />
          <div class="border"></div>
          <div class="searched_res_amenities_chosen_div">
            <br />
            <h4 class="default_green_color">Amenities</h4>
            <br />
            <% if @reservation[:amenity_details].nil? %>
            <p><strong>•No Amenities Chosen.</strong></p>
            <% else %>
              <% JSON.parse(@reservation[:amenity_details]).each do |name, description, price, quanity| %>
                <strong><%= "•#{name}: #{description}" %></strong>
                <br />
                <strong><%= "$#{price} x #{quanity}" %></strong>
                <br />
                <br />
              <% end %>
            <% end %>
          </div>
          <br />
          <div class="border"></div>
          <div class="searched_res_total_price_div">
            <br />
            <h4 class="default_green_color">Total Price</h4>
            <br />
            <strong>$<%= @reservation[:total_price] %></strong>
          </div>
          <br />
          <br />
          <div class="border"></div>
          <br />
          <br />
        </div>
      </div>
    </div>
  </div>
</body>