config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  root to: "home#index"
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :controllers => { registrations: "devise_registrations", passwords: "devise_passwords" }
  get "/users/sign_in" => redirect("/")

  resources :home
  resources :contact_messages, only: [:new, :create]
  resources :customer_emergency_contacts, only: [:edit, :new, :create, :update, :destroy]
  resources :customer_vet_infos, only: [:edit, :new, :create, :update, :destroy]
  resources :hours_of_operations, only: [:edit, :update, :create, :destroy]
  resources :holidays
  resources :breed_restrictions
  resources :pets, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :amenities, only: [:new, :create, :update, :destroy, :edit]
  resources :policies, only: [:new, :create, :update, :destroy, :edit]
  resources :photos, only: [:new, :create, :update, :destroy, :edit]
  get '/reservations/old', to: "reservations#old_reservations", as: :old_reservation
  get '/get_pets', to: "reservations#get_pets", as: :get_pets

  resources :reservations, only: [:show, :new, :create]
  resources :kennel_ratings, only: [:new, :create]
  resources :stand_by_reservations, only: [:new, :create]
  resources :check_in_check_out_reservations, only: [:update]
  resources :check_in_contract_important_informations, only: [:update, :edit]
  resources :check_in_contract_reservation_changes, only: [:update, :edit]
  resources :check_in_contract_refund_policies, only: [:update, :edit]
  resources :press_pages

  # CsvKennelsController
    resources :csv_kennels
    post '/notify_kennel', to: 'csv_kennels#notify_kennel', as: :notify_kennel
    get '/claim_business', to: 'csv_kennels#claim_business', as: :claim_business
    post '/send_business_claim', to: 'csv_kennels#send_business_claim', as: :send_business_claim


  # PawbookingsAdminsController
   resources :pawbookings_admins, only: [:index]
   get '/admin_reservation_search', to: "pawbookings_admins#admin_reservation_search", as: :admin_reservation_search

   get '/refund_reservation_select', to: "pawbookings_admins#refund_reservation_select", as: :refund_reservation_select
   get '/refund_reservation_confirm', to: "pawbookings_admins#refund_reservation_confirm", as: :refund_reservation_confirm

   get '/update_reservation', to: "pawbookings_admins#update_reservation", as: :update_reservation

  # RunsController
    resources :runs, only: [:new, :create, :update, :destroy, :edit]
    delete "/delete_run_image", to: "runs#delete_run_image", as: :delete_run_image

  # PaymentsController
    resources :payments, only: [:new, :create]
    get "/vaccination_upload_after_payment", to: "payments#vaccination_upload_after_payment", as: :vaccination_upload_after_payment

  # KennelsController
    resources :kennels, only: [:new, :create, :update, :show, :edit, :index, :destroy]
    get "/kennel_dashboard",   to: "kennels#kennel_dashboard",   as: :kennel_dashboard
    get "/kennel_reservations", to: "kennels#kennel_reservations", as: :kennel_reservations
    get "/kennel_view_pets", to: "kennels#kennel_view_pets", as: :kennel_view_pets
    get '/search_reservations', to: "kennels#search_reservations", as: :search_reservations
    match "/kennel_searched_reservation", to: "kennels#kennel_searched_reservation", as: :kennel_searched_reservation, via: [:get, :post]

  # CustomersController
    get "/customer_dashboard", to: "customers#customer_dashboard", as: :customer_dashboard
    post "/create_user_image", to: "customers#create_user_image", as: :create_user_image
    delete "/delete_user_image", to: "customers#delete_user_image", as: :delete_user_image

  # SearchesController
    resources :searches, only: [:create]
    get "/search_results", to: "searches#search_results", as: :search_results

  # BlogsController
    resources :blogs
    match "/blog_search", to: "blogs#blog_search", as: :blog_search, via: [:get, :post]
    get "/all_blogs", to: "blogs#all_blogs", as: :all_blogs

  # BlogCategoriesController
    resources :blog_categories
    get "/all_blog_categories", to: "blog_categories#all_blog_categories", as: :all_blog_categories

  # Contracts
    match "/customer_checkin_contract", to: "contracts#customer_checkin_contract", as: :customer_checkin_contract, via: [:get, :post]

  # HomeController
    get "/kennel_or_customer", to: "home#kennel_or_customer", as: :kennel_or_customer
    get "/about", to: "home#about", as: :about
    get "/faq", to: "home#faq", as: :faq
    get "/policies_and_terms", to: "home#policies_and_terms", as: :policies_and_terms
    get "/changes_cancellations_refunds", to: "home#changes_cancellations_refunds", as: :changes_cancellations_refunds
    get "/terms_of_service", to: "home#terms_of_service", as: :terms_of_service
    get "/privacy_policy", to: "home#privacy_policy", as: :privacy_policy

  # Contact
    get "/message_confirmation", to: "contact_messages#message_confirmation", as: :message_confirmation


end

app/models/search.rb
class Search < ApplicationRecord
  validates :search_zip, format: { with: /\A[0-9]{5}\z/i, message: "Zip-Code requires 5 numbers." }
  validates :radius, format: { with: /\A[0-9]{0,3}\z/i, message: "Radius accepts no more than 3 numbers." }
  validates :check_in, presence: { message: "Must give a check-in date."}
  validates :check_out, presence: { message: "Must give a check-out date."}
  validates :cats_or_dogs, presence: true
  validates :number_of_dogs, format: { with: /\A[0-9]{1}\z/i }
  validates :number_of_cats, format: { with: /\A[0-9]{1}\z/i }
  validates :number_of_rooms, format: { with: /\A[0-9]{1,2}\z/i }
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  skip_before_action :verify_authenticity_token
  include SearchesHelper

  def create
    dates_split = params[:reservation_dates].split(" ")
    params[:check_in] = dates_split[0]
    params[:check_out] = dates_split[2]
    if (params[:number_of_dogs].to_i > 0) && (params[:number_of_cats].to_i == 0)
      params[:cats_or_dogs] = "dogs"
    elsif (params[:number_of_dogs].to_i == 0) && (params[:number_of_cats].to_i > 0)
      params[:cats_or_dogs] = "cats"
    else
      params[:cats_or_dogs] = "both"
    end
    search = Search.new

    sanitize_date(params[:check_in])
    params[:check_in] = Date.parse(@new_date)
    sanitize_date(params[:check_out])
    params[:check_out] = Date.parse(@new_date)

    search.search_zip = params[:search_zip].to_i
    search.radius = params[:radius].to_i
    search.check_in = params[:check_in]
    search.check_out = params[:check_out]
    search.cats_or_dogs = params[:cats_or_dogs]
    search.number_of_dogs = params[:number_of_dogs].to_i
    search.number_of_cats = params[:number_of_cats].to_i
    search.number_of_rooms = params[:number_of_rooms].to_i
    if search.valid? && search.save
      redirect_to search_results_path(params)
    else
      flash[:notice] = search.errors.messages.values.flatten[0].to_s
      redirect_to request.referrer
    end
  end

  def search_results
    if params[:no_params].nil?
      if params[:number_of_dogs] == "0" && params[:number_of_cats] == "0"
        flash[:notice] = "Must select number of dogs or cats greater than 0."
        return redirect_to request.referrer
      end

      @final_search_results = []
      get_pet_stay_dates
      location_filtering
      pet_type_filtering
      # holiday_filtering
      hours_of_operation_filtering
      check_if_runs_listed
      # @final_search_results = Kennel.last(20)
    end
  end

  def get_pet_stay_dates
    @pet_stay_date_range = (Date.parse(params[:check_in])..Date.parse(params[:check_out])).map{|date| date}
    params[:number_of_nights] = (@pet_stay_date_range.count.to_i - 1) > 0 ? (@pet_stay_date_range.count.to_i - 1) : 1
  end

  def location_filtering
    params[:radius] = "5" if params[:radius].blank?
    @relevant_locations = Kennel.where(taken_ownership: true).near(params[:search_zip], params[:radius]).to_a
    return @relevant_locations
  end

  def pet_type_filtering
    @pet_type_filtered_results = []
    @relevant_locations.each do |rl|
      if params[:cats_or_dogs] == "both"
        @pet_type_filtered_results = @relevant_locations
      else
        if rl.cats_or_dogs == "both" || rl.cats_or_dogs == params[:cats_or_dogs]
          @pet_type_filtered_results << rl
        end
      end
    end
  end

  # def holiday_filtering
  #   @kennels_with_holidays = []
  #   @pet_type_filtered_results.each do |fr|
  #     kennel = Kennel.find(fr.id)
  #     holidays = Holiday.where(kennel_id: kennel[:id])
  #     holidays.each do |h|
  #       @pet_stay_date_range.each { |ps| @kennels_with_holidays << kennel if ps === h.holiday_date }
  #     end
  #   end
  #   @negative_kennels = @kennels_with_holidays
  #   @kennels_with_holidays.each do |k|
  #     @pet_type_filtered_results.each do |pt|
  #       @pet_type_filtered_results.delete pt if pt === k
  #     end
  #   end
  #   @holiday_filtered_results = @pet_type_filtered_results
  # end

  def hours_of_operation_filtering
    @kennels_that_are_closed = []
    @negative_kennels = []
    # @pet_type_filtered_results.each do |fr|
    #   kennel = Kennel.find(fr.id)
    #   hours_of_operation = HoursOfOperation.where(kennel_id: kennel[:id])
    #   @kennels_that_are_closed << kennel if hours_of_operation.empty?
    #   puts hours_of_operation.to_a
    #   hours_of_operation.to_a.each do |h|
    #     counter = 0
    #     @pet_stay_date_range.each do |ps|
    #       days_of_week.each do |num, day|
    #         counter += 1 if ps.wday.to_s == num && h.send(day) == "closed"
    #       end
    #     end
    #     @kennels_that_are_closed << kennel if counter > 0
    #   end
    # end
    # @kennels_that_are_closed.each do |k|
    #   @negative_kennels << k
    #   @pet_type_filtered_results.each do |fr|
    #     @pet_type_filtered_results.delete fr if k === fr
    #   end
    # end
    @hours_of_operation_results = @pet_type_filtered_results
  end

  def check_if_runs_listed
    @hours_of_operation_results.each do |hr|
      runs = Run.where(kennel_id: hr.id)
      @final_search_results << hr if !runs.empty?
    end
    get_csv_kennels
  end

  def get_csv_kennels
    relevant_locations = Kennel.near(params[:search_zip], params[:radius]).where(taken_ownership: false).reverse.to_a
    relevant_locations.each do |rl|
      @final_search_results << rl
    end
    @final_search_results.reverse!
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
  def cat_or_dog_options
    [
      ['Dog', 'dogs'],
      ['Cat', 'cats'],
      ['Cat & Dog', 'both']
    ]
  end

  def days_of_week
    [
      ["1", "monday_open"],
      ["2", "tuesday_open"],
      ["3", "wednesday_open"],
      ["4", "thursday_open"],
      ["5", "friday_open"],
      ["6", "saturday_open"],
      ["7", "sunday_open"],
    ]
  end
end

app/views/searches/search_results.html.erb
<%= render partial: "shared/top_info" %>

<div class="search_container" style="padding-top:7em;text-align:center;padding-bottom:1em;">
  <h1 style="text-shadow:1px 1px 18px black;" class="default_white_color arvo_font text_underline">Search for Kennels:</h1>
  <div class="search_parent_div hidden_if_mobile" style="color:black;">
    <div class="row no_left_right_margin">
      <div class="col-md-1"></div>
      <div class="col-xs-12 col-md-4">
        <% if controller_name == "searches" && action_name == "search_results" %>
          <div class="fixed_search_bar">
            <%= render partial: "shared/search_bar" %>
          </div>
        <% end %>
      </div>
      <div class="col-md-7">
        <% if !@final_search_results.blank? %>
            <% @final_search_results.reverse.each do |fr| %>
              <div class="search_results_individual_div">
                <% if fr[:taken_ownership] %>
                  <h4><%= link_to fr.name, kennel_path(fr, search_info: params), class:"searched_kennel_title_link default_green_color" %></h4>
                <% else %>
                  <h4><%= link_to fr.name, csv_kennel_path(id: fr), class:"searched_kennel_title_link default_green_color" %></h4>
                <% end %>
                <p class="kennel_show_address"><span class="glyphicon glyphicon-map-marker"></span> <%= "#{fr[:address]} #{fr[:city]}, #{fr[:state]} #{fr[:zip]}" %></p>
                <% if fr[:taken_ownership] %>
                  <p class="search_results_mission_statement"><%= truncate(fr.mission_statement, length: 150, omission: "... ") %><%= link_to "read more", kennel_path(fr, search_info: params) %></p>
                <% else %>
                  <p class="search_results_mission_statement"><%= link_to "read more", csv_kennel_path(id: fr) %></p>
                <% end %>
                <br />
                <div class="row margin_top_n1em text-center">
                  <div class="col-xs-4">
                    <%= image_tag fr.avatar.url(:thumb), class:"border_radius_100 kennel_dashboard_avatar" %>
                  </div>
                  <div class="col-xs-4">
                    <% if fr[:taken_ownership] %>
                      <p class="text-center view_details_btn"><%= link_to "View Details", kennel_path(fr, search_info: params), class: "default_white_color btn btn-success" %></p>
                    <% else %>
                      <p class="text-center view_details_btn"><%= link_to "View Details", csv_kennel_path(id: fr), class: "default_white_color btn btn-success" %></p>
                    <% end %>
                  </div>
                  <div class="col-xs-4">
                    <% if fr.cats_or_dogs == "both" %>
                      <img class="pet_icon" src="/assets/dog_icon.png"><img class="pet_icon" src="/assets/cat_icon.png">
                    <% elsif fr.cats_or_dogs = "dogs" %>
                      <img class="pet_icon" src="/assets/dog_icon.png">
                    <% elsif fr.cats_or_dogs = "cats" %>
                      <img class="pet_icon" src="/assets/cat_icon.png">
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <p class="text-center no_results_found default_white_color poppins_font">No results found…</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row no_left_right_margin hidden_if_desktop">
    <div class="col-xs-12">
      <%= render partial: "shared/search_bar" %>
      <% if !@final_search_results.blank? %>
          <% @final_search_results.reverse.each do |fr| %>
            <div class="search_results_individual_div">
              <% if fr[:taken_ownership] %>
                <h4><%= link_to fr.name, kennel_path(fr, search_info: params), class:"searched_kennel_title_link default_green_color" %></h4>
              <% else %>
                <h4><%= link_to fr.name, csv_kennel_path(id: fr), class:"searched_kennel_title_link default_green_color" %></h4>
              <% end %>
              <p class="kennel_show_address"><span class="glyphicon glyphicon-map-marker"></span> <%= "#{fr[:address]} #{fr[:city]}, #{fr[:state]} #{fr[:zip]}" %></p>
              <% if fr[:taken_ownership] %>
                <p class="search_results_mission_statement"><%= truncate(fr.mission_statement, length: 150, omission: "... ") %><%= link_to "read more", kennel_path(fr, search_info: params) %></p>
              <% else %>
                <p class="search_results_mission_statement"><%= truncate(fr.mission_statement, length: 150, omission: "... ") %><%= link_to "read more", csv_kennel_path(id: fr) %></p>
              <% end %>
              <div class="row margin_top_n1em text-center">
                <div class="col-xs-4">
                  <%= image_tag fr.avatar.url(:thumb), class:"border_radius_100 kennel_dashboard_avatar" %>
                </div>
                <div class="col-xs-4">
                  <% if fr[:taken_ownership] %>
                    <p class="text-center view_details_btn"><%= link_to "View Details", kennel_path(fr, search_info: params), class: "default_white_color btn btn-success" %></p>
                  <% else %>
                    <p class="text-center view_details_btn"><%= link_to "View Details", csv_kennel_path(id: fr), class: "default_white_color btn btn-success" %></p>
                  <% end %>
                </div>
                <div class="col-xs-4">
                  <% if fr.cats_or_dogs == "both" %>
                    <img class="pet_icon" src="/assets/dog_icon.png"><img class="pet_icon" src="/assets/cat_icon.png">
                  <% elsif fr.cats_or_dogs = "dogs" %>
                    <img class="pet_icon" src="/assets/dog_icon.png">
                  <% elsif fr.cats_or_dogs = "cats" %>
                    <img class="pet_icon" src="/assets/cat_icon.png">
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <p class="text-center no_results_found default_white_color">No results found…</p>
      <% end %>
    </div>
  </div>
</div>

<!-- <%# if !@negative_kennels.blank? %>
  <h1>The Kennels listed below do NOT meet your reservation dates selected.</h1>
  <%# @negative_kennels.each do |fr| %>
    <%#= link_to fr.name, search_path(fr.id, search_info: params) %>
    <br>
    <%# if fr.cats_or_dogs == "both" %>
      Cats and Dogs
    <%# else %>
      <%#= fr.cats_or_dogs.capitalize %>
    <%# end %>
    <br>
    <%#= fr.address %>
    <br>
    <br>
  <%# end %>
<%# end %> -->

<div class="relative_position">
  <%= render partial: "shared/footer" %>
</div>